#!/bin/zsh
set -u
root="${0:A:h:h}"; validator="$root/scripts/validate-profile.mjs"; sample="$root/examples/generic-git-site-profile.json"
node "$validator" "$sample" >/dev/null || exit 1
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
expect64(){ node "$validator" "$1" >/dev/null 2>&1; [[ $? -eq 64 ]] || { print -u2 -- "expected rejection: $1"; exit 1; }; }
jq '.core_policy_version="serpsmith-core-v7"' "$sample" > "$tmp/core.json"; expect64 "$tmp/core.json"
jq 'del(.repository_instruction_files)' "$sample" > "$tmp/instructions.json"; expect64 "$tmp/instructions.json"
jq '.timezone="Not/A-Timezone"' "$sample" > "$tmp/timezone.json"; expect64 "$tmp/timezone.json"
jq '.image_directory="/absolute/not-allowed"' "$sample" > "$tmp/path.json"; expect64 "$tmp/path.json"
jq '.private_key="forbidden"' "$sample" > "$tmp/secret.json"; expect64 "$tmp/secret.json"
jq '.unknown_policy=true' "$sample" > "$tmp/unknown.json"; expect64 "$tmp/unknown.json"
jq '.search_integrations={google:{required:true}}' "$sample" > "$tmp/stale-search.json"; expect64 "$tmp/stale-search.json"
jq 'del(.sitemap_url)' "$sample" > "$tmp/missing-sitemap.json"; expect64 "$tmp/missing-sitemap.json"
jq '.sitemap_url="https://example.com/sitemap.xml?token=forbidden"' "$sample" > "$tmp/sitemap-query.json"; expect64 "$tmp/sitemap-query.json"
jq '.schedule={weekdays:["monday","funday"],local_time:"09:00",timezone:"UTC",slot_key:"0900"}' "$sample" > "$tmp/weekdays.json"; expect64 "$tmp/weekdays.json"
jq '.schedule={weekdays:["monday"],local_time:"09:00",timezone:"UTC",slot_key:"0900",unknown:true}' "$sample" > "$tmp/schedule-unknown.json"; expect64 "$tmp/schedule-unknown.json"
jq '.branch="../unsafe"' "$sample" > "$tmp/branch.json"; expect64 "$tmp/branch.json"
jq '.article_route="https://example.com/blog/<slug>"' "$sample" > "$tmp/route.json"; expect64 "$tmp/route.json"
jq '.image_policy.hero_quality=101' "$sample" > "$tmp/image-quality.json"; expect64 "$tmp/image-quality.json"
jq '.image_policy.strip_metadata="yes"' "$sample" > "$tmp/image-boolean.json"; expect64 "$tmp/image-boolean.json"
jq '.external_link_limits={sources_minimum:5,sources_maximum:3}' "$sample" > "$tmp/link-limits.json"; expect64 "$tmp/link-limits.json"
jq '.search_console_property="sc-domain:other-site.com"' "$sample" > "$tmp/domain.json"; expect64 "$tmp/domain.json"
jq '.analytics.property_id="G-ABCDE12345"' "$sample" > "$tmp/analytics-id.json"; expect64 "$tmp/analytics-id.json"
jq '.analytics.expected_hostname="other.com"' "$sample" > "$tmp/analytics-host.json"; expect64 "$tmp/analytics-host.json"
jq '.analytics.windows_days=[7,30,90]' "$sample" > "$tmp/analytics-windows.json"; expect64 "$tmp/analytics-windows.json"
jq '.analytics.key_events=["cta_click","cta_click"]' "$sample" > "$tmp/analytics-events.json"; expect64 "$tmp/analytics-events.json"
jq '.analytics.credential_path="/tmp/key.json"' "$sample" > "$tmp/analytics-secret.json"; expect64 "$tmp/analytics-secret.json"
jq '.autopilot_enabled=true' "$sample" > "$tmp/autopilot.json"; expect64 "$tmp/autopilot.json"
print -r -- "profile validation tests passed"
